---
title: "p8105_hw5_pm3148"
author: "Pooja Mukund"
date: "11/16/2021"
output: github_document
---

```{r}
#Load Libaries
library(tidyverse)
library(viridis)
```

# Problem 1 

```{r}
#Load Data
homicide<- read_csv("data/homicide-data.csv", na = c("", "Unknown"))

homicide_cln<-homicide%>%
  mutate(city_state = str_c(city, ",", state),
         resolution = case_when(disposition=="Closed without arrest" ~ "unsolved", 
                                disposition=="Open/No arrest" ~ "unsolved", 
                                disposition=="Closed by arrest" ~ "solved"))%>%
  relocate(city_state)%>%
  filter(city_state !="Tulsa,AL")

```

```{r}
baltimore_df<- homicide_cln%>%
 filter(city_state=="Baltimore,MD")

baltimore_summary<- baltimore_df%>%
  summarize(
    unsolved = sum(resolution=="unsolved"),
    n=n()
  )

baltimore_test<-prop.test(
          x = baltimore_summary%>%pull(unsolved), 
          n = baltimore_summary%>%pull(n)
          )

baltimore_test%>%
  broom::tidy()
```
# Create prop test function
```{r}
prop_test_function<-function(city_df){
  city_summary = 
    city_df%>%
    summarize(
      unsolved = sum(resolution=="unsolved"),
    n=n()
  )
  
  city_test = 
    prop.test(x = city_summary%>%pull(unsolved), 
          n = city_summary%>%pull(n))
  return(city_test)
}

prop_test_function(baltimore_df)
```

#Iterate over entire dataset
```{r}
nested_df<-
  homicide_cln%>%
  nest(data = uid:resolution)%>%
  mutate(test_results = map(data, prop_test_function),
         tidy_results = map(test_results, broom::tidy))

nested_df%>%
  filter(city_state=="Baltimore,MD")%>%
  pull(tidy_results)

results_df<-
  homicide_cln%>%
  nest(data = uid:resolution)%>%
  mutate(test_results = map(data, prop_test_function),
         tidy_results = map(test_results, broom::tidy))%>%
  select(city_state, tidy_results)%>%
  unnest(tidy_results)%>%
  select(city_state, estimate, starts_with("conf"))


```

Make plot with Geom Error Bar
```{r}
results_df%>%
  mutate(city_state = fct_reorder(city_state, estimate))%>%
  ggplot(aes(x = city_state, y=estimate)) + 
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1))+xlab("City,State")+ylab("Proportion Estimate")
```
# Problem 2 

```{r}
file_path = "data/study"
files<-list.files(path = file_path, full.names = FALSE)

files<-
  files%>%
  rename(file_name = `list.files(path = file_path, full.names = FALSE)`)

study_cln<-
  data_frame(filename = files)%>%
  mutate(file_contents = map(filename, ~ read_csv(file.path("data/study", .))),
         arm = str_extract(filename, "con|exp"),
         subject_id =str_extract(filename, "\\d+"))%>%
  unnest(file_contents)%>%
  select(-filename)%>%
  relocate(subject_id, arm)

```

